### ISSUE TITLE
What is the best way to export spesific sheets from book to PDF? 

### ISSUE THREAD

**Issue by oshliaer** [tanaikech/PDFApp#1]
Hi!

Thanks a lot for this great lib! You're awesome.

Can you answer What is the best way to export spesific sheets from book to PDF?

**Comment by tanaikech** [comment]
Thank you for your comment. I apologize for the late response.

From your comment, I understand that you want to export specific sheets from a Google Spreadsheet as a PDF. Is that correct?

If so, here are two approaches you can consider:

- Approach 1 (Simpler Method):
	1. Hide the sheets you don't want to export.
	2. Export the spreadsheet as a PDF.
	3. (Optional) Show all sheets again.

- Approach 2 (More Complex Method):
	1. Export the specific sheets individually as PDFs using a URL like this (replace {spreadsheetId} with your spreadsheet ID and {sheetId} with the ID of the specific sheet): `https://docs.google.com/spreadsheets/d/{spreadsheetId}/export?format=pdf&gid={sheetId}`
	2. Merge the separate PDFs into a single PDF using this library.

I guess that approach 1 is generally recommended due to its lower process cost. If I misunderstood your comment, I apologize.

**Comment by oshliaer** [comment]
Oh! Thank you!

You undestand me correct.

I'm using the Approach 2 every time. I didn't know about the first method.

There is a method of my classic `class App`

```js
 async sendBookSheetsToTelegram() {
    const names = ['Лист20', 'Лист21'];
    const ids = names.map((name) => this.book.getSheetByName(name)?.getSheetId()).filter(Boolean);

    const data = ids.map((id) => {
      const url = `https://docs.google.com/spreadsheets/export?exportFormat=pdf&id=${this.book.getId()}&&gid=${id}&printnotes=false`;
      const blob = UrlFetchApp.fetch(url, {
        headers: { authorization: `Bearer ${ScriptApp.getOAuthToken()}` },
      }).getBlob();
      return new Uint8Array(blob.getBytes());
    });

    const pdfDoc = await this.pdfService.PDFLibA.PDFDocument.create();

    for (let i = 0; i < data.length; i++) {
      const pdfData = await this.pdfService.PDFLibA.PDFDocument.load(data[i]);
      const pages = await pdfDoc.copyPages(
        pdfData,
        [...Array(pdfData.getPageCount())].map((_, i) => i),
      );
      pages.forEach((page) => pdfDoc.addPage(page));
    }
    const bytes = await pdfDoc.save();

    this.telegram.sendDocument(Utilities.newBlob([...new Int8Array(bytes)], 'application/pdf', 'report.pdf'));
  }
```

Thank you so much.

**Comment by tanaikech** [comment]
Thank you for replying. I think that if the Spreadsheet is used with multiple users, pattern 1 might be not suitable, because the sheets are hidden suddenly when the script is run.
